### ISSUE TITLE
Maybe incorrect "Usage restrictions" for PodChaos

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/website#231]
I noticed that there is a description of PodChaos:

> Currently, Chaos Mesh only supports fault injection to certain types of Pod, such as Deployment, StatefulSet, and DaemonSet. Chaos Mesh does not support injecting faults into an independent Pod. An independent Pod means a Pod that is not bound to ReplicaSet or Deployment Pod.

https://github.com/chaos-mesh/website/blame/master/docs/simulate-pod-chaos-on-kubernetes.md#L17

I think Chaos Mesh could inject PodChaos into "independent Pod", but there is no guarantee for the "application/system" could recover to normal, because there is no upper layer controller to reconcile pods to "desired state"

I think the description needs updates.

FYI @g1eny0ung @YangKeao

**Comment by g1eny0ung** [comment]
I think so. With permission, we can inject PodChaos on any pods. As far as getting back to the desired state, I don't think we have a guarantee at this time.

**Comment by YangKeao** [comment]
@cwen0 PTAL
