### ISSUE TITLE
Broken links for Vector Wasm Transformer

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/website#290]
https://github.com/chaos-mesh/website/blob/2d24e569e8603c9db05254fea1993481d3dd42e2/blog/2021-06-25-chaos-mesh-remake-one-step-closer-toward-chaos-as-a-service.md?plain=1#L137

I saw that here is an update in #286. But it still failed with 404

**Comment by STRRL** [comment]
PTAL @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
Can't find the cache again, I think we can remove the link
