### ISSUE TITLE
switch versioned documentation would not change the URL

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/website#349]
This issue happens with versioned documentation 2.3.1.

For example:

1. I am watching the `Next` version documentation now:
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/20221408/189848291-ed5b0398-5990-49db-9056-32f6e8dc1dab.png">

2. then I switch to the `2.3.1` version, the content and the tag have updated, but the URL NOT.

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/20221408/189848490-e3064fcc-8e33-41e4-80ba-22da1ffa1131.png">

3. I switch to the `2.2.3` version, all of the content, tag and the URL changed:

<img width="1221" alt="image" src="https://user-images.githubusercontent.com/20221408/189848679-c9363517-2185-4b4a-80de-41b97e22dfb4.png">

It would mislead the URL when someone wants to share the documentation.

And I think it might be related to thsi file: https://github.com/chaos-mesh/website/blob/0aa15b0896fdd5a7781e23a86b6f7e5fef489404/versioned_sidebars/version-2.3.1-sidebars.json

In the former `versione_x.x.x-sidebar.json` file, each entry would specify the certain id with version prefix, like:

```json
    {
      "type": "category",
      "label": "Tools Integration",
      "items": [
        {
          "type": "doc",
          "id": "version-2.2.3/integrate-chaos-mesh-into-github-actions"
        },
        {
          "type": "doc",
          "id": "version-2.2.3/use-grafana-data-source"
        },
        {
          "type": "doc",
          "id": "version-2.2.3/chaosctl-tool"
        }
      ],
      "collapsible": true,
      "collapsed": true
    },
```

but in `version-2.3.1-sidebars.json`, it becomes;

```json
    {
      "type": "category",
      "label": "Tools Integration",
      "items": [
        "integrate-chaos-mesh-into-github-actions",
        "use-grafana-data-source",
        "chaosctl-tool"
      ]
    },
```

exactly same with the outer `sidebar.json`.

It seems the behaviors changes of `yarn docusaurus docs:version 2.3.1` makes this issue.

**Comment by STRRL** [comment]
PTAL :heart: @g1eny0ung

**Comment by g1eny0ung** [comment]
This is expected behavior. The latest released docs (`v2.3.1` in this case) will be placed under the `docs/` path.

**Comment by g1eny0ung** [comment]
Wait...I need to check it.

**Comment by g1eny0ung** [comment]
@STRRL I think I got it.

This behavior is normal after checking. You can refer to this URL: https://docusaurus.io/docs/versioning#terminology.

And why `version-2.3.1-sidebars.json` does not have versioned prefixes in each item, I guess this is an enhancement. The latest version of Docusaurus will distinguish versions based on filenames.

**Comment by g1eny0ung** [comment]
> It would mislead the URL when someone wants to share the documentation.

I don't think it will be a problem. Most users can know our releases if he/she can take a moment to think briefly about it. 😉

**Comment by STRRL** [comment]
> @STRRL I think I got it.
> 
> This behavior is normal after checking. You can refer to this URL: https://docusaurus.io/docs/versioning#terminology.
> 
> And why `version-2.3.1-sidebars.json` does not have versioned prefixes in each item, I guess this is an enhancement. The latest version of Docusaurus will distinguish versions based on filenames.

Great. : )



> > It would mislead the URL when someone wants to share the documentation.
> 
> I don't think it will be a problem. Most users can know our releases' distribution if they can take a moment to think briefly about it. wink

I got that. I think we do not need to update that policy until someone bothers with that.
