### ISSUE TITLE
Grafana already has ChaosMesh plugin, so https://chaos-mesh.org/docs/use-grafana-data-source/ is outdated

### ISSUE THREAD

**Issue by fzyzcjy** [chaos-mesh/website#392]
Hi, Grafana already has ChaosMesh plugin, so https://chaos-mesh.org/docs/use-grafana-data-source/ is outdated :)

See https://grafana.com/grafana/plugins/chaosmeshorg-datasource/

**Comment by MA3CIN** [comment]
Good point - i can take it from here

**Comment by MA3CIN** [comment]
I adjusted the docs in this PR - https://github.com/chaos-mesh/website/pull/396
@g1eny0ung Can i ask you to link this issue (#392) to this PR (https://github.com/chaos-mesh/website/pull/396)?

**Comment by g1eny0ung** [comment]
> I adjusted the docs in this PR - #396 @g1eny0ung Can i ask you to link this issue (#392) to this PR (#396)?

Done. :)
