### ISSUE TITLE
Improve i18n Support for Hardcoded Text on Chaos Mesh Website

### ISSUE THREAD

**Issue by tfinardi** [chaos-mesh/website#420]
### Problem
Currently, some texts on the Chaos Mesh website are hardcoded in English, making them unavailable for translation via the i18n system. This creates a suboptimal experience for non-English users, as the website displays English text regardless of the selected language.

For example:
```html
<h2 className="tw-text-4xl xl:tw-text-5xl">
  Make <span className={styles.heroTitle}>Cloud Native + Chaos Engineering</span> simple and straightforward.
</h2>
<p className="lg:tw-text-lg tw-font-medium">
  Based on the principles of Chaos Engineering, Chaos Mesh abstracts real-world events into objects that can be directly applied, hiding the trivial details.
</p>
```

### Proposed Solution

Refactor hardcoded text to use the <Translate /> component from the i18n library, allowing these texts to be translated. For instance:

```html
<h2 className="tw-text-4xl xl:tw-text-5xl">
  <Translate id="home.headings.4">Make</Translate> 
  <span className={styles.heroTitle}> Cloud Native + Chaos Engineering </span> 
  <Translate id="home.headings.5">simple and straightforward.</Translate>
</h2>
<p className="lg:tw-text-lg tw-font-medium">
  <Translate id="home.paragraph">
    Based on the principles of Chaos Engineering, Chaos Mesh abstracts real-world events into objects that can be directly applied, hiding the trivial details.
  </Translate>
</p>
```

### Benefits

- Enables better localization and accessibility for non-English users.
- Improves the international reach of the Chaos Mesh website.
- Aligns with best practices for maintaining a globally inclusive project.

**Comment by Andrewmatilde** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
@tfinardi @Andrewmatilde Thanks for both suggestions. Yes, this is a known issue. When I did it before, in pursuit of quickly rebuilding the entire new version of the website, I was lazy here. I left many more hardcoded English texts with no i18n process done for them.

I plan to make this improvement this afternoon and not delay this issue any longer.

**Comment by g1eny0ung** [comment]
I have completed part of the work on #421.

**Comment by g1eny0ung** [comment]
I have completed part of the work on #421.
